name: CI Workflow
on: [push]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Print contents in current directory
        run: ls -la
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
