name: CI Workflow
on: [push]

jobs:
  build-and-test:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository in ubuntu's file system
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Print contents in current directory
        run: ls -la
      - name: Create properties file
        run: |
            touch secrets.properties
            echo GITHUB_ACCESS_TOKEN="${{ secrets.EXPLORE_GITHUB_ACCESS_TOKEN }}" >> secrets.properties
            echo GITHUB_BASE_URL="${{ secrets.EXPLORE_GITHUB_BASE_URL }}" >> secrets.properties
            cat secrets.properties
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports
